language: ruby
rvm:
  - 2.7.0
services:
  - postgresql
  - xvfb
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - psql -c 'create database sumo_city_test;' -U postgres
test:
  adapter: postgresql
  database: sumo_city_test
dist: trusty
sudo: required
addons:
  chrome: stable
  postgresql: "9.6"
before_install:
  - # start your web application and listen on `localhost`
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  # You can add here your credentials

development:
  <<: *default
  database: sumo_city_development

test:
  <<: *default
  database: sumo_city_test

production:
  <<: *default
  database: sumo_city_production


