dist: trusty
sudo: required
addons:
  chrome: stable
  postgresql: "9.6"
  apt:
    packages:
      - chromium-chromedriver
language: ruby
rvm:
  - 2.7.0

services:
  - postgresql
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin
  - RAILS_ENV=test ./bin/rails assets:precompile
  - psql -c 'create database sumo_city_test;' -U postgres
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
  - nvm install 8.16.0
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  # You can add here your credentials

development:
  <<: *default
  database: sumo_city_development

test:
  <<: *default
  database: sumo_city_test

production:
  <<: *default
  database: sumo_city_production
