dist: trusty
addons:
  firefox: latest
  postgresql: "9.6"
language: ruby
rvm:
  - 2.7.0
services:
  - postgresql
script:
  - bundle exec rake
before_script:
  - RAILS_ENV=test ./bin/rails assets:precompile
  - psql -c 'create database sumo_city_test;' -U postgres
before_install:
  - nvm install 8.16.0

